name: pull-request-checks
run-name: pull-request-checks for ${{ github.head_ref }}

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "release" }
          - { os: windows-latest, r: "4.2.0" }
          - {
              os: ubuntu-latest,
              r: "release",
              rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest",
            }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6

      - uses: r-hub/actions/setup-r-sysreqs@v1
        with:
          type: full

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

  integration-tests-main:
    name: integration-tests (others main)
    needs: R-CMD-check
    uses: SticsRPacks/SticsRTests/.github/workflows/integration-tests.yaml@main
    with:
      repo: CroptimizR
      ref: ${{ github.head_ref }}
      sha: ${{ github.event.pull_request.head.sha }}
      dependency_mode: main
      sticsrtests_ref: main
    secrets: inherit

  integration-tests-release:
    name: integration-tests (others release)
    needs: R-CMD-check
    uses: SticsRPacks/SticsRTests/.github/workflows/integration-tests.yaml@main
    with:
      repo: CroptimizR
      ref: ${{ github.head_ref }}
      sha: ${{ github.event.pull_request.head.sha }}
      dependency_mode: release
      sticsrtests_ref: main
    secrets: inherit
